name: release

on: 
  workflow_dispatch:
    
jobs:

  # ============================================================================

  test:    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]

    steps:
    
    - name: Checkout repositry
      uses: actions/checkout@v2

    - name: Retrieve version from pyproject.toml
      run: echo ::set-env name=PROJECT_VERSION::$(awk '/^version/{print $NF}' pyproject.toml | tr -d '"' | tr -d "'")

    - name: tag-exists-action
      uses: mukunku/tag-exists-action@v1.0.0
      id: checkTag
      with: 
        tag: releases/${{ env.PROJECT_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check if version tag exists
      run: if ${{ steps.checkTag.outputs.exists }} == true; then exit 1; fi

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v2
    
    - name: Install dependencies
      run: poetry install
    
    - name: Lint with flake8
      run: poetry run flake8 --config .flake8 --statistics

    - name: Run Pytest
      run: poetry run pytest --cov=./ --cov-report=xml

    - name: Run Pytest multiprocess
      run: |
        mkdir -p /tmp/test_multiproc
        export prometheus_multiproc_dir=/tmp/test_multiproc
        poetry run pytest -k test_multiprocess_reg --cov-append --cov=./ --cov-report=xml
        rm -rf /tmp/test_multiproc
        unset prometheus_multiproc_dir

    - name: Code Coverage
      uses: codecov/codecov-action@v1.0.11
      if: matrix.python-version == 3.8
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Run black formatter
      if: matrix.python-version == 3.8
      run: poetry run black .

    - name: Run isort
      if: matrix.python-version == 3.8
      run: poetry run isort .

    - name: Recommit
      if: matrix.python-version == 3.8
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply auto-formatting [skip ci]
        file_pattern: ./*.py
        commit_user_name: My GitHub Actions Bot
        commit_user_email: tim.schwenke+github@protonmail.ch

    - name: Build package
      run: poetry build

  # ============================================================================

  release-to-pypi:
    needs: test
    
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repositry
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry and setup cache
        uses: Gr1N/setup-poetry@v2
      
      - name: Install dependencies
        run: poetry install

      - name: Build
        run: poetry build
      
      - name: Release
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}

  # ============================================================================

  create-github-release:
    needs: release-to-pypi

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repositry
        uses: actions/checkout@v2

      - name: Retrieve version
        run: echo ::set-env name=PROJECT_VERSION::$(awk '/^version/{print $NF}' pyproject.toml | tr -d '"' | tr -d "'")

      - name: Retrieve change
        run: awk '/\[${{ env.PROJECT_VERSION }}\]/{flag=1; next} /\[.*\]/{flag=0} flag' CHANGELOG.md > github-release-body.md

      - name: Retrieve date
        run: echo "::set-env name=NOW::$(date +'%Y-%m-%d')"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: releases/${{ env.PROJECT_VERSION }}
          release_name: "[${{ env.PROJECT_VERSION }}] ${{ env.NOW }}"
          body_path: github-release-body.md
          draft: false
          prerelease: false
